# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: log.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'log.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlog.proto\x1a\x1bgoogle/protobuf/empty.proto\"~\n\x08LogEntry\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x14\n\x0cid_instancia\x18\x02 \x01(\x05\x12\x10\n\x08marcador\x18\x03 \x01(\t\x12\n\n\x02ip\x18\x04 \x01(\t\x12\r\n\x05\x61lias\x18\x05 \x01(\t\x12\x0e\n\x06\x61\x63\x63ion\x18\x06 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x07 \x01(\t2:\n\nLogService\x12,\n\x07SendLog\x12\t.LogEntry\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGENTRY']._serialized_start=42
  _globals['_LOGENTRY']._serialized_end=168
  _globals['_LOGSERVICE']._serialized_start=170
  _globals['_LOGSERVICE']._serialized_end=228
# @@protoc_insertion_point(module_scope)
