# Autogenerated from proto_server/log.proto for Elixir gRPC client
# To use with :grpc and :protobuf

# This file is no longer needed as we have successfully generated log.pb.ex
# using the setup_grpc_codegen.ps1 script.
#
# The actual implementation is now in log.pb.ex

# This file is kept for reference only and is not used in the application.
# It can be safely deleted.

# See log.pb.ex for the actual implementation.
